---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-2
  labels:
    app: jenkins-2
spec:
  ports:
    - nodePort: 32000
      port: 80
      targetPort: 8080
  selector:
    app: jenkins-2
    tier: jenkins-2
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-2
  labels:
    app: jenkins-2
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins-2
        tier: jenkins-2
    spec:
      containers:
        - name: jenkins-2
          image: adimicoli/my-jenkins-image:1.0
          securityContext:
            privileged: true
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}