#apiVersion: v1
#kind: Service
#metadata:
#  name: web
#  namespace: testing
#  labels:
#    app: galaxy
#    service: web
#spec:
#  ports:
#    - nodePort: 31100
#      port: 80
#      targetPort: 80
#  selector:
#    app: galaxy
#    tier: web
#  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: testing
  labels:
    app: galaxy
    service: web
spec:
  selector:
    app: galaxy
    service: web
  ports:
  - protocol: TCP
    targetPort: 8000
    name: port-8000-tcp
    port: 8000

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: testing
  labels:
    app: galaxy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        tier: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-persistent-storage
        persistentVolumeClaim:
          claimName: nginx-claim
