### TODO
### Persistent Volume Claims - pending
### pod has unbound PersistentVolumeClaims - error

kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/nginx/"

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-claim
  namespace: testing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi