- name: Create a testing namespace
  k8s:
    name: testing
    api_version: v1
    kind: Namespace
    state: present

- name: Create a Nginx Deployment by reading the definition from a local file
  k8s:
    state: present
    definition: "{{ lookup('file', 'nginx-deployment.yml') | from_yaml }}"

- name: Create a Nginx Persistent Volume by reading the definition from a local file
  k8s:
    state: present
    definition: "{{ lookup('file', 'nginx-persistent_volume.yml') | from_yaml }}"