---
- name: Disable swap
  command: swapoff -a

- name: Install kubernetes
  block:
    - name: 'Add kubernetes repo key'
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      become: true
    - name: Add kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io kubernetes-xenial main
        state: present
        filename: 'kubernetes'
      become: true
    - name: Install kubernetes components
      apt: 'name={{item}} state=present update_cache=yes'
      with_items:
        - kubelet
        - kubeadm
        - kubectl
        - kubernetes-cni
      become: true

- name: Initialize master - step 1
  become: true
  command: "{{ item }}"
  ignore_errors: True
  with_items:
    - kubeadm init

- name: Initialize master - step 2
  become: true
  ignore_errors: True
  command: "{{ item }}"
  with_items:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config

- name: Deploy Dashboard
  command: kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  ignore_errors: yes