---
- name: determine if docker is installed
  shell: which docker
  register: docker_installed
#   ignore_errors: true
  changed_when: false

# - name: get docker version
#   shell: docker --version | awk '{ print $3 }'
#   register: docker_installed_version
#   when: docker_installed|success
#   changed_when: false

# - name: install or upgrade docker
#   shell: curl https://releases.rancher.com/install-docker/{{ docker_version }}.sh | sh
#   when: not docker_installed|success or
#         not docker_installed_version.stdout|search(docker_version|string)

# - name: make sure docker is running
#   service: name=docker state=started enabled=true